title:              Kumar APP
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://thevolts.github.io

author:
  name:             Your Name
  url:              https://twitter.com/thevolts
  email:            thevolts@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
